### ISSUE TITLE
RSS Link URL is not a url, it's a fragment

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [pablouser1/ProxiTok#112]
**Describe the bug**
Link URLs in RSS feed are not complete URLs

**To Reproduce**
1. Open any Proxitok RSS feed post
2. Click on Link, for example "/@shopheav3n/video/7174585288365460782"
This is not a full URL

**Expected behavior**
Should see a complete URL that's able to load in a browser.

**Logs**
NA

**Enviroment (please complete the following information):**

Using https://tok.habedieeh.re
Frontend version: 2.4.3.1
Scraper version: 2.3.2.1

Also https://proxitok.esmailelbob.xyz
Frontend version: 2.4.3.6
Scraper version: 2.3.3.1

**Comment by tinglycraniumplacidly** [comment]
Also, tysm for proxitok! I use it almost exclusively for RSS/just to get updates on accounts.

**Comment by pablouser1** [comment]
Hi! That's probably because those instances do not have the `APP_URL` env variable properly configured (more info [here](https://github.com/pablouser1/ProxiTok/wiki/Configuration)).

That variable defaults to '/' when undefined, which works OK for HTML but not for RSS. This was not properly explained in the past, which resulted on most of the Docker deploys to always default to '/'.

Now is properly explained in the [self-hosting wiki article](https://github.com/pablouser1/ProxiTok/wiki/Self-hosting).

**Comment by tinglycraniumplacidly** [comment]
Thanks! I found an instance that set it properly https://tok.artemislena.eu/ =D
