### ISSUE TITLE
<meta property tags are no longer filled correctly.

### ISSUE THREAD

**Issue by TrashAccount3424** [pablouser1/ProxiTok#137]
<meta property tags are no longer filled correctly.

Some instances show the following error on top of the page.

![aa](https://user-images.githubusercontent.com/49032809/227518087-ffebb426-235b-47e7-ba0a-efaa9a1cad33.png)

Example :https://proxitok.esmailelbob.xyz/@vancityreynolds

Frontend version: 2.4.7.0 Scraper version: 2.3.6.0

**Comment by NoPlagiarism** [comment]
Can't reproduce on Firefox
What browser are you using?

**Comment by TrashAccount3424** [comment]
> Can't reproduce on Firefox What browser are you using?

Its not browser related. However the error only shows up the first time a profile page is loaded.
So that means you have to open a user page no one else opened on that instance before i guess.

The actual problem itself (the meta tags not getting filled) can be seen if you look at the source code of a user profile page.
There is comment `<!-- Using TikTok's meta config --> ` and below that are the tags which are mostly empty but previously where filled with the actual data about the user.

**Comment by NoPlagiarism** [comment]
Oh, sorry for that

**Comment by pablouser1** [comment]
Hi @TrashAccount3424, thanks for pointing it out. Looks like TikTok changed the attribute `SEO` from `SIGI_STATE` to `SEOState`. It has been fixed with pablouser1/TikScraperPHP@7e296d1ff871b81ed5f2bc9756308272148cd96f. Now it returns everyting like it should:
![Captura de pantalla de 2023-03-29 11-24-52](https://user-images.githubusercontent.com/17802865/228490158-a226158f-7c79-4079-a9c1-e5c5d9bf47ce.png)

Please confirm that it also works on your end

**Comment by TrashAccount3424** [comment]
Tested and seems to work perfectly again 👍
