### ISSUE TITLE
403 on user page 

### ISSUE THREAD

**Issue by GodSaveTheDoge** [pablouser1/ProxiTok#25]
The user page shows 403 instead of _something_

Example: https://proxitok.herokuapp.com/@roro.cat

**Comment by GodSaveTheDoge** [comment]
Unrelated but the redirector pattern looks wrong (?). 

https://vm.tiktok.com/ZMLja28XQ/ gets redirected to https://proxitok.herokuapp.com/ZMLja28XQ/ which is a 404.
It should be https://proxitok.herokuapp.com/@placeholder/video/ZMLja28XQ instead.

**Comment by pablouser1** [comment]
> The user page shows 403 instead of _something_
> 
> Example: https://proxitok.herokuapp.com/@roro.cat

That is because the official instance is being rate limited by TikTok. The only "fix" to this is using another ProxiTok instance or waiting some hours. I also added a robots.txt to the project, almost all of the requests made to the instance were just bots.


> Unrelated but the redirector pattern looks wrong (?).
> 
> https://vm.tiktok.com/ZMLja28XQ/ gets redirected to https://proxitok.herokuapp.com/ZMLja28XQ/ which is a 404. It should be https://proxitok.herokuapp.com/@placeholder/video/ZMLja28XQ instead.

Probably because `Include pattern: (.*//.*)(tiktok.com)(.*)` redirects _all_ subdomains to proxitok.herokuapp.com, changing it to _only_ www would do the trick. You would have to make at least 1 connection to the TikTok servers though. As far as I'm aware, Libredirect also uses this method.

**Comment by GodSaveTheDoge** [comment]
> You would have to make at least 1 connection to the TikTok servers though

I see. Multiple patterns might be needed then

**Comment by pablouser1** [comment]
I'm closing this issue for now... It looks like TikTok doesn't return a 403 anymore when the rate limit is triggered
