### ISSUE TITLE
docker container error non zero code on Dockerfile

### ISSUE THREAD

**Issue by bugbounted** [pablouser1/ProxiTok#43]
Hi [Pablo Ferreiro](https://github.com/pablouser1),
I'm trying to deploy your code on k8s container but return non zero code on dockerfile build , i think it's because dockerfile isn't standard for direct read from contaniers & it must start from docker-compose . please make changs on Dockerfile to work direct build correctly.
waiting for your commit/s.
finest regards

**Comment by pablouser1** [comment]
Hi, hopefully bdba336d3c5fee76206299e0a61c04c95edfd163 fixes this issue. I'm now able to build the ProxiTok image without using docker-compose. Remember that you need to send the enviromental variables necessary with the -e flag and create a volume for Latte cache.

**Comment by elmirarokni** [comment]
hello again pablo ,
your dockerfile is'nt standard to read directly from containers , please pick one standard docker build from hub.docker.com & put run & changes cmds after build from that standard docker.at this time , dockerfile can't build without non zero code , see my build log error in action :

workspace is ready.
--
2 | Step 1/8 : FROM php:8-apache
3 | ---> af944036d594
4 | Step 2/8 : WORKDIR /var/www/html
5 | ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
6 | ---> Running in 211c7a7a9e29
7 | Removing intermediate container 211c7a7a9e29
8 | ---> a9e4b32780fb
9 | Step 3/8 : COPY --from=composer /usr/bin/composer /usr/bin/composer
10 | ---> 123c429f26f2
11 | Step 4/8 : RUN apt update -y && apt upgrade -y && apt install -y --no-install-recommends libzip-dev && pecl install redis zip && docker-php-ext-enable redis zip && a2enmod rewrite headers && mkdir /cache && chown -R www-data:www-data /cache && rm -rf /var/www/html/*
12 | ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
13 | ---> Running in b13290696034
14 | [91m
15 | WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
16 |  
17 | [0mGet:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
18 | Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
19 | Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
20 | Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [153 kB]
21 | Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
22 | Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2592 B]
23 | Fetched 8537 kB in 2s (4534 kB/s)
24 | Reading package lists...
25 | Building dependency tree...
26 | Reading state information...
27 | All packages are up to date.
28 | [91m
29 | WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
30 |  
31 | [0mReading package lists...
32 | Building dependency tree...
33 | Reading state information...
34 | Calculating upgrade...
35 | 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
36 | [91m
37 | [0m[91mWARNING: apt does not have a stable CLI interface. Use with caution in scripts.
38 |  
39 | [0mReading package lists...
40 | Building dependency tree...
41 | Reading state information...
42 | The following additional packages will be installed:
43 | libzip4 zlib1g-dev
44 | The following NEW packages will be installed:
45 | libzip-dev libzip4 zlib1g-dev
46 | 0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
47 | Need to get 409 kB of archives.
48 | After this operation, 1070 kB of additional disk space will be used.
49 | Get:1 http://deb.debian.org/debian bullseye/main amd64 libzip4 amd64 1.7.3-1 [55.4 kB]
50 | Get:2 http://security.debian.org/debian-security bullseye-security/main amd64 zlib1g-dev amd64 1:1.2.11.dfsg-2+deb11u1 [191 kB]
51 | Get:3 http://deb.debian.org/debian bullseye/main amd64 libzip-dev amd64 1.7.3-1 [163 kB]
52 | [91mdebconf: delaying package configuration, since apt-utils is not installed
53 | [0mFetched 409 kB in 1s (707 kB/s)
54 | Selecting previously unselected package libzip4:amd64.
55 | (Reading database ... (Reading database ... 5% (Reading database ... 10% (Reading database ... 15% (Reading database ... 20% (Reading database ... 25% (Reading database ... 30% (Reading database ... 35% (Reading database ... 40% (Reading database ... 45% (Reading database ... 50% (Reading database ... 55% (Reading database ... 60% (Reading database ... 65% (Reading database ... 70% (Reading database ... 75% (Reading database ... 80% (Reading database ... 85% (Reading database ... 90% (Reading database ... 95% (Reading database ... 100% (Reading database ... 14119 files and directories currently installed.)
56 | Preparing to unpack .../libzip4_1.7.3-1_amd64.deb ...
57 | Unpacking libzip4:amd64 (1.7.3-1) ...
58 | Selecting previously unselected package zlib1g-dev:amd64.
59 | Preparing to unpack .../zlib1g-dev_1%3a1.2.11.dfsg-2+deb11u1_amd64.deb ...
60 | Unpacking zlib1g-dev:amd64 (1:1.2.11.dfsg-2+deb11u1) ...
61 | Selecting previously unselected package libzip-dev:amd64.
62 | Preparing to unpack .../libzip-dev_1.7.3-1_amd64.deb ...
63 | Unpacking libzip-dev:amd64 (1.7.3-1) ...
64 | Setting up libzip4:amd64 (1.7.3-1) ...
65 | Setting up zlib1g-dev:amd64 (1:1.2.11.dfsg-2+deb11u1) ...
66 | Setting up libzip-dev:amd64 (1.7.3-1) ...
67 | Processing triggers for libc-bin (2.31-13+deb11u3) ...
68 | downloading redis-5.3.7.tgz ...
69 | Starting to download redis-5.3.7.tgz (275,200 bytes)
70 | .........................................................done: 275,200 bytes
71 | downloading zip-1.20.1.tgz ...
72 | Starting to download zip-1.20.1.tgz (351,117 bytes)
73 | ...done: 351,117 bytes
74 | 31 source files, building
75 | running: phpize
76 | Configuring for:
77 | PHP Api Version: 20210902
78 | Zend Module Api No: 20210902
79 | Zend Extension Api No: 420210902
80 | enable igbinary serializer support? [no] : enable lzf compression support? [no] : enable zstd compression support? [no] : building in /tmp/pear/temp/pear-build-defaultuserI5293M/redis-5.3.7
81 | running: /tmp/pear/temp/redis/configure --with-php-config=/usr/local/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no
82 | ls: cannot access '.': Operation not permitted
83 | configure: error: working directory cannot be determined
84 | ERROR: `/tmp/pear/temp/redis/configure --with-php-config=/usr/local/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no' failed
85 | The command '/bin/sh -c apt update -y && apt upgrade -y && apt install -y --no-install-recommends libzip-dev && pecl install redis zip && docker-php-ext-enable redis zip && a2enmod rewrite headers && mkdir /cache && chown -R www-data:www-data /cache && rm -rf /var/www/html/*' returned a non-zero code: 1

**Comment by cron410** [comment]
Seems to be working fine for me.
